//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bin
    {
        public int BinID { get; set; }
        public Nullable<int> DocumentID { get; set; }
        public Nullable<int> Customer { get; set; }
        public Nullable<System.DateTime> DateBuy { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Document Document { get; set; }
    }
}
