//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DocumentsEntities : DbContext
    {
        public DocumentsEntities()
            : base("name=DocumentsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<Bin> Bins { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Comment> Comments { get; set; }
        public virtual DbSet<Guestbook> Guestbooks { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Theard> Theards { get; set; }
        public virtual DbSet<WishList> WishLists { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<News> News { get; set; }
        public virtual DbSet<Document> Documents { get; set; }
    }
}
