//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Document
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Document()
        {
            this.Bins = new HashSet<Bin>();
            this.Comments = new HashSet<Comment>();
            this.WishLists = new HashSet<WishList>();
        }
    
        public int DocumentID { get; set; }
        public string DocumentName { get; set; }
        public string DocumentContent { get; set; }
        public string DocumentDescription { get; set; }
        public Nullable<int> DocumentPoint { get; set; }
        public Nullable<System.DateTime> DatePost { get; set; }
        public Nullable<int> PostBy { get; set; }
        public byte[] Thumbnail { get; set; }
        public string Tag { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public Nullable<double> Rate { get; set; }
        public string DocumentFile { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Bin> Bins { get; set; }
        public virtual Category Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WishList> WishLists { get; set; }
    }
}
