//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int NewsID { get; set; }
        public string NewsTitle { get; set; }
        public string Description { get; set; }
        public string NewsContent { get; set; }
        public byte[] Thumbnail { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<int> TheardID { get; set; }
        public string Tag { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual Theard Theard { get; set; }
    }
}
